force-app/main/default/objects/DispatchInstruction__c/DispatchInstruction__c.object-meta.xml
<CustomObject>
    <label>Instructions</label>
    <nameField>
        <displayFormat>I- {00000000}</displayFormat>
        <label>Unique ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchInstruction__c/fields/Audience__c.field-meta.xml
<CustomField>
    <fullName>Audience__c</fullName>
    <label>Audience</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Scheduler</fullName>
            </value>
            <value>
                <fullName>GCC/LAP/LAT</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DispatchInstruction__c/fields/CreatedByUserName__c.field-meta.xml
<CustomField>
    <fullName>CreatedByUserName__c</fullName>
    <formula>CreatedBy.Username</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CreatedByUserName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DispatchInstruction__c/fields/Instruction__c.field-meta.xml
<CustomField>
    <fullName>Instruction__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DispatchInstruction__c/fields/Type_of_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Instruction__c</fullName>
    <label>Type of Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DispatchInstruction__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <label>Visibility</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal (Private)</fullName>
                <default>true</default>
                <label>Internal (Private)</label>
            </value>
            <value>
                <fullName>External (Public)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DispatchInstruction__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Instructions</relationshipLabel>
    <relationshipName>Instructions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ConvergeInstructionHandler.cls
public with sharing class ConvergeInstructionHandler {

/*
Component : dispatchInstructionsLWC
Description: Method used for retrieving filtered data for the Instructions component
Change Log:
===============================================================================================
Date                Author                  UserStory#               Change Description
===============================================================================================
05-jan-2020         Caue Neves            Defect 7521045                   Initial Version
*/
    @AuraEnabled( cacheable=true )  
    public static List <DispatchInstruction__c> fetchWOInstructions( String parRecordId )  {  

        return [SELECT Id, Name, CreatedById, Audience__c, Instruction__c, Work_Order__c, Visibility__c, 
                       Type_of_Instruction__c, CreatedByUserName__c, LastModifiedById
                FROM DispatchInstruction__c
                WHERE Work_Order__c = :parRecordId 
                AND Soft_Deleted__c = false
                ORDER BY Name ASC];
                                                             
    }  

}